### ISSUE TITLE
Error: Task git-clone(0.9) requires Tekton Pipelines min version v0.38.0 but found v0.37.5

### ISSUE THREAD

**Issue by snp116** [ibm-developer-skills-network/wtecc-CICD_PracticeCode#13]
Two labs : 
  1. Hands-on Lab: Integrating Unit Test Automation 
  2. Hands-on Lab: Use Tekton Continuous Delivery (CD) Catalog
**have some dependency issue for tekton cli.**
When running this - 
`tkn hub install task git-clone`
it gives this error: 
Error: Task git-clone(0.9) requires Tekton Pipelines min version v0.38.0 but found v0.37.5
I tried get new update using this cmd:
`kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`

but still gives error I guess due to permission issue/codespace 

So I used prev version (0.8) of the required task.. and then it was able to install the required task...hope that helps me to complete the lab.

**Comment by rofrano** [comment]
@snp116 Thanks for bringing this to our attention. We've looked into this and the problem is that the support team updated the Tekton CLI (`tkn`) but did not, and cannot, update Tekton Pipelines to match due to a problem with the OpenShift Operator not offering the latest version.

The workaround we suggest is to install `git-clone` manually from the Tekton Hub without using `tkn` by applying the yaml manifest yourself using `kubectl` or `oc`. This will bypass the version check:

```bash
kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
```

We have updated the lab instructions to add this workaround while we work on a more final solution.

Alternately you can downgrade the Tekton client. Either will work.

**Comment by snp116** [comment]
Thank you so much for the response Sir.  Successfully completed it with the above kubectl cmd.
